In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("weight-height.csv")
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [3]:
#use z score to remove outliers
df["zscore"]=(df.Height - df.Height.mean())/df.Height.std()
df.head(20)

   Gender     Height      Weight    zscore
0    Male  73.847017  241.893563  1.943964
1    Male  68.781904  162.310473  0.627505
2    Male  74.110105  212.740856  2.012343
3    Male  71.730978  220.042470  1.393991
4    Male  69.881796  206.349801  0.913375
5    Male  67.253016  152.212156  0.230136
6    Male  68.785081  183.927889  0.628331
7    Male  68.348516  167.971110  0.514865
8    Male  67.018950  175.929440  0.169301
9    Male  63.456494  156.399676 -0.756607
10   Male  71.195382  186.604926  1.254786
11   Male  71.640805  213.741169  1.370554
12   Male  64.766329  167.127461 -0.416171
13   Male  69.283070  189.446181  0.757762
14   Male  69.243732  186.434168  0.747538
15   Male  67.645620  172.186930  0.332177
16   Male  72.418317  196.028506  1.572635
17   Male  63.974326  172.883470 -0.622019
18   Male  69.640060  185.983958  0.850546
19   Male  67.936005  182.426648  0.407650

In [4]:
no_outlier_zscore=df[(df.zscore<3) & (df.zscore>-3)]
no_outlier_zscore.head(20)

   Gender     Height      Weight    zscore
0    Male  73.847017  241.893563  1.943964
1    Male  68.781904  162.310473  0.627505
2    Male  74.110105  212.740856  2.012343
3    Male  71.730978  220.042470  1.393991
4    Male  69.881796  206.349801  0.913375
5    Male  67.253016  152.212156  0.230136
6    Male  68.785081  183.927889  0.628331
7    Male  68.348516  167.971110  0.514865
8    Male  67.018950  175.929440  0.169301
9    Male  63.456494  156.399676 -0.756607
10   Male  71.195382  186.604926  1.254786
11   Male  71.640805  213.741169  1.370554
12   Male  64.766329  167.127461 -0.416171
13   Male  69.283070  189.446181  0.757762
14   Male  69.243732  186.434168  0.747538
15   Male  67.645620  172.186930  0.332177
16   Male  72.418317  196.028506  1.572635
17   Male  63.974326  172.883470 -0.622019
18   Male  69.640060  185.983958  0.850546
19   Male  67.936005  182.426648  0.407650

In [5]:
no_outlier_zscore.to_csv('outlier_weight_height.csv')

In [6]:
no_outlier_zscore

      Gender     Height      Weight    zscore
0       Male  73.847017  241.893563  1.943964
1       Male  68.781904  162.310473  0.627505
2       Male  74.110105  212.740856  2.012343
3       Male  71.730978  220.042470  1.393991
4       Male  69.881796  206.349801  0.913375
...      ...        ...         ...       ...
9995  Female  66.172652  136.777454 -0.050658
9996  Female  67.067155  170.867906  0.181830
9997  Female  63.867992  128.475319 -0.649655
9998  Female  69.034243  163.852461  0.693090
9999  Female  61.944246  113.649103 -1.149651

[9993 rows x 4 columns]

In [7]:
total_val=no_outlier_zscore.shape[0]+1
total_val

9994

In [8]:
def x_formula():
    square_x=(no_outlier_zscore["Height"]**2)
    total_x=0
    for i in square_x:
        i=total_x+i
        return i
x_formula()

5453.38192238515

In [9]:
def variance_x():
    return (x_formula()/total_val)-(no_outlier_zscore["Height"].mean())**2
variance_x()

-4403.615695043177

In [10]:
def y_formula():
    square_y=(no_outlier_zscore["Weight"]**2)
    total_x=0
    for i in square_y:
        i=total_x+i
        return i
y_formula()

58512.495908128076

In [11]:
def variance_y():
    return (y_formula()/total_val)-(no_outlier_zscore["Height"].mean())**2
variance_x()

-4403.615695043177

In [12]:
def x_y_formula():
    multiply_x_y=(no_outlier_zscore["Height"]*no_outlier_zscore["Weight"])
    total_x=0
    for i in multiply_x_y:
        i=total_x+i
        return i
x_y_formula()

17863.11807661307

In [13]:
def variance_x_y():
    return (x_y_formula()()/total_val)-(x_y_formula().mean())**2
variance_x()

-4403.615695043177

In [15]:
def co_varance():
    return (variance_x_y()/sqrt(variance_x*variance_y))
co_varance()

TypeError: 'float' object is not callable